> Initialized logger
>  * Restarting with stat
> Exception in thread Malaria Detection:
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\detector.py", line 63, in run
>     self.query()
>   File "C:\Users\gherz-PC\Desktop\remidiv2\serveus\detector.py", line 80, in query
>     img = [f for f in os.listdir(chunklist.filename) if f[-4:] == ".jpg" or f[-4:] == ".png"]
> WindowsError: [Error 3] The system cannot find the path specified: u'20190310_202624_dinmt_9303769_32\\*.*'
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
