> Initialized logger
> Exception in thread Malaria Detection:
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\threading.py", line 801, in __bootstrap_inner
>     self.run()
> TypeError: run() takes no arguments (1 given)
>  * Debugger is active!
>  * Debugger PIN: 456-115-780
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
> 192.168.137.9 - - [10/Mar/2019 21:10:58] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.9 - - [10/Mar/2019 21:10:59] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.9 - - [10/Mar/2019 21:10:59] "POST /api/db/ HTTP/1.1" 200 -
>  * Detected change in 'C:\\Users\\gherz-PC\\Desktop\\remidiv2\\serveus\\detector.py', reloading
