> Initialized logger
> Exception in thread Malaria Detection:
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\threading.py", line 801, in __bootstrap_inner
>     self.run()
> TypeError: run() takes no arguments (1 given)
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
>  * Restarting with stat
