> Initialized logger
>  * Debugger is active!
>  * Debugger PIN: 456-115-780
>  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
> 127.0.0.1 - - [13/Mar/2019 10:26:30] "GET / HTTP/1.1" 302 -
> 127.0.0.1 - - [13/Mar/2019 10:26:31] "GET /monitoring/1/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:26:33] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:26:33] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:26:33] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:26:34] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:26:34] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:26:36] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:26:36] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:26:36] "POST /api/db/ HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Mar/2019 10:26:42] "GET /records/1 HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Mar/2019 10:26:47] "GET /logout/ HTTP/1.1" 302 -
> 127.0.0.1 - - [13/Mar/2019 10:26:47] "GET /index HTTP/1.1" 301 -
> C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py:90: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
>   return render_template("index.html",login_form = LoginForm(), recovery_form = RecoveryForm())
> C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py:90: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
>   return render_template("index.html",login_form = LoginForm(), recovery_form = RecoveryForm())
> 127.0.0.1 - - [13/Mar/2019 10:26:48] "GET /index/ HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Mar/2019 10:26:49] "GET /static/js/sha1.js HTTP/1.1" 200 -
> C:\Users\gherz-PC\Desktop\remidiv2\serveus\views.py:769: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
>   form = LoginForm()
> 127.0.0.1 - - [13/Mar/2019 10:26:55] "POST /login/ HTTP/1.1" 302 -
> 127.0.0.1 - - [13/Mar/2019 10:26:55] "GET /monitoring/1 HTTP/1.1" 301 -
> 127.0.0.1 - - [13/Mar/2019 10:26:56] "GET /monitoring/1/ HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Mar/2019 10:27:00] "GET /records/1 HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Mar/2019 10:27:04] "GET /case/7/ HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Mar/2019 10:27:20] "GET /records/2 HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Mar/2019 10:27:23] "GET /case/6/ HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Mar/2019 10:27:23] "GET /thumb/pic/28 HTTP/1.1" 301 -
> 127.0.0.1 - - [13/Mar/2019 10:27:25] "GET /thumb/pic/28/ HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Mar/2019 10:27:40] "POST /case/6/ HTTP/1.1" 200 -
> 127.0.0.1 - - [13/Mar/2019 10:28:01] "GET /case/6/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:28:01] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:28:02] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:28:28] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:28:28] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:28:29] "POST /api/db/ HTTP/1.1" 200 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 654, in __init__
>     self.finish()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\socket.py", line 283, in close
>     self.flush()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 10054] An existing connection was forcibly closed by the remote host
> 192.168.137.31 - - [13/Mar/2019 10:28:38] "POST /api/db/ HTTP/1.1" 200 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 654, in __init__
>     self.finish()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\socket.py", line 283, in close
>     self.flush()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 10054] An existing connection was forcibly closed by the remote host
> 192.168.137.31 - - [13/Mar/2019 10:28:41] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:28:41] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:28:42] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:29:20] "POST /api/db/ HTTP/1.1" 200 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 654, in __init__
>     self.finish()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\socket.py", line 283, in close
>     self.flush()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 10054] An existing connection was forcibly closed by the remote host
> 192.168.137.31 - - [13/Mar/2019 10:29:36] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:29:36] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:29:37] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:30:06] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:30:06] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:30:07] "POST /api/db/ HTTP/1.1" 200 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 654, in __init__
>     self.finish()
> 192.168.137.31 - - [13/Mar/2019 10:30:26] "POST /api/validation/ HTTP/1.1" 200 -
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\socket.py", line 283, in close
>     self.flush()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 10054] An existing connection was forcibly closed by the remote host
> 192.168.137.31 - - [13/Mar/2019 10:30:26] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:30:27] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:32:04] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:32:04] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:32:05] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:32:47] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:32:47] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:32:51] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:33:20] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:33:20] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:33:21] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:34:32] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:34:32] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:34:33] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:35:00] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:35:00] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:35:01] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:39:31] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:39:31] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:39:32] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:39:55] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:39:55] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 10:39:56] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 11:08:13] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 11:08:13] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 11:08:15] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:08:15] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:08:15] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:08:17] "POST /api/db/ HTTP/1.1" 200 -
> Traceback (most recent call last):
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 654, in __init__
>     self.finish()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\socket.py", line 283, in close
>     self.flush()
>   File "C:\Users\gherz-PC\Anaconda3\envs\py27\lib\socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 10054] An existing connection was forcibly closed by the remote host
> 192.168.137.31 - - [13/Mar/2019 13:08:25] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:08:26] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:08:26] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:08:55] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:08:55] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:09:58] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:09:58] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:09:59] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:10:53] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:10:53] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:10:54] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:34:30] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:34:30] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:34:30] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:35:30] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:35:30] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:35:31] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:36:38] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:36:38] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:36:38] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:36:39] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:36:39] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:36:50] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:36:50] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 13:36:51] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:04:19] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:04:19] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:04:20] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:04:21] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:04:21] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:04:43] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:04:43] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:04:43] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:06:11] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:06:11] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:06:11] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:06:16] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:06:16] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:06:27] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:06:27] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:06:27] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:07:49] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:07:49] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:07:49] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:07:51] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:07:51] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:09:39] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:09:39] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:09:39] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:09:56] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:09:56] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:09:56] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:10:17] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:10:17] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:10:26] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:10:26] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:10:26] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:11:15] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:11:15] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:11:16] "POST /api/db/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:11:16] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:11:16] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:12:10] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:12:10] "POST /api/validation/ HTTP/1.1" 200 -
> 192.168.137.31 - - [13/Mar/2019 14:12:10] "POST /api/db/ HTTP/1.1" 200 -
>  * Detected change in 'C:\\Users\\gherz-PC\\Desktop\\remidiv2\\serveus\\models.py', reloading
